// Prebuild step (Step 4B M4): turns content/site.json into App Router files. For every page after the
// home page it writes app/<slug>/page.tsx (a two-line file that renders that page), and it writes
// lib/type.generated.ts with only the chosen type pairing, so the site loads two font files, not five.
// No content text is ever written into code: generated files hold only a validated slug or a pairing
// name, both checked here against strict patterns. Folders this script made carry a .generated marker
// and are removed before each run, so a renamed page cannot leave a stale route behind.
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const app = path.join(root, "app");
const site = JSON.parse(readFileSync(path.join(root, "content/site.json"), "utf-8"));

const SLUG = /^[a-z][a-z0-9-]{0,39}$/;
const RESERVED = new Set(["index", "api", "fonts", "not-found"]);

for (const entry of readdirSync(app, { withFileTypes: true })) {
  if (entry.isDirectory() && existsSync(path.join(app, entry.name, ".generated"))) rmSync(path.join(app, entry.name), { recursive: true });
}

const pages = site.pages ?? [];
if (pages[0]?.slug !== "index") throw new Error('content: pages[0].slug must be "index"');
for (const page of pages.slice(1)) {
  if (!SLUG.test(page.slug) || RESERVED.has(page.slug)) throw new Error(`content: page slug ${JSON.stringify(page.slug)} is not allowed`);
  const dir = path.join(app, page.slug);
  if (existsSync(dir)) throw new Error(`content: page slug ${page.slug} collides with a starter folder`);
  mkdirSync(dir);
  writeFileSync(path.join(dir, ".generated"), "");
  writeFileSync(
    path.join(dir, "page.tsx"),
    `import { PageView, pageMetadata } from "@/components/PageView";\n\nexport const metadata = pageMetadata(${JSON.stringify(page.slug)});\n\nexport default function Page() {\n  return <PageView slug=${JSON.stringify(page.slug)} />;\n}\n`,
  );
}

// next/font needs literal arguments at module scope, so the chosen pairing is written out as code.
const FACES = {
  bricolage: ["bricolage-grotesque/files/bricolage-grotesque-latin-wght-normal.woff2", "200 800", '"ui-sans-serif", "system-ui", "sans-serif"'],
  newsreader: ["newsreader/files/newsreader-latin-wght-normal.woff2", "200 800", '"ui-serif", "Georgia", "serif"'],
  archivo: ["archivo/files/archivo-latin-wdth-normal.woff2", "100 900", '"ui-sans-serif", "system-ui", "sans-serif"'],
  geist: ["geist/files/geist-latin-wght-normal.woff2", "100 900", '"ui-sans-serif", "system-ui", "sans-serif"'],
  hanken: ["hanken-grotesk/files/hanken-grotesk-latin-wght-normal.woff2", "100 900", '"ui-sans-serif", "system-ui", "sans-serif"'],
};
// studio: characterful grotesque + neutral text; editorial: sharp text serif + grotesque; technical: expanded width axis + neutral text.
const PAIRINGS = { studio: ["bricolage", "geist"], editorial: ["newsreader", "hanken"], technical: ["archivo", "geist"] };
const pairing = site.brand?.typePairing;
if (!Object.hasOwn(PAIRINGS, pairing)) throw new Error(`content: brand.typePairing ${JSON.stringify(pairing)} is not one of ${Object.keys(PAIRINGS).join(", ")}`);
const [display, text] = PAIRINGS[pairing];
const face = (name, variable) => {
  const [file, weight, fallback] = FACES[name];
  return `localFont({\n  src: "../node_modules/@fontsource-variable/${file}",\n  variable: "${variable}",\n  weight: "${weight}",\n  display: "swap",\n  fallback: [${fallback}],\n})`;
};
writeFileSync(
  path.join(root, "lib/type.generated.ts"),
  `// Generated by scripts/routes.mjs from brand.typePairing ("${pairing}"). Do not edit.\nimport localFont from "next/font/local";\n\nexport const displayFace = ${face(display, "--font-display")};\nexport const textFace = ${face(text, "--font-text")};\n`,
);
console.log(`routes: ${pages.length} page(s), type pairing ${pairing}`);
