/**
 * Step 4B M1 acceptance for the claims gate, run against real files:
 * - the Step 4 artifact (byte-identical to checkpoint sha256 960b61ba…, downloaded from the private
 *   artifacts bucket 2026-10-01) FAILS on the leaked tool text, the unlabelled testimonials and the
 *   invented phone/hours, exactly the defects the human review found and the original six missed;
 * - the clean fixture passes every check in QA_GATE_CHECKS;
 * - each planted claims fixture fails its own check and only that one.
 * Fixtures are generated by packages/rendered-qa/scripts/make-fixtures.ts (synthetic client).
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import path from "node:path";
import { CHECK_REGISTRY, CLAIMS_CHECKS, QA_GATE_CHECKS, runChecks } from "../src/registry.js";
import { VerificationLoop } from "../src/verificationLoop.js";
import { MockModelClient } from "../src/modelClient.js";
import type { AsyncCheckSuite, CheckResult, VerificationContext } from "../src/checks/types.js";

const repo = path.resolve(import.meta.dirname, "..", "..", "..");
const read = (rel: string) => readFileSync(path.join(repo, rel), "utf-8");
const brief = JSON.parse(read("clients/summit-line-roofing/brief.json")) as { goal: string; brandNotes: string; requiredSections: string[] };
const STEP4 = "packages/verification/test/fixtures/step4-summit-line-960b61ba.html";

function ctx(html: string, factSources: string[] | undefined = [brief.goal, brief.brandNotes]): VerificationContext {
  return { html, clientSlug: "summit-line-roofing", requiredSections: brief.requiredSections, otherClientSlugs: ["dreamsign-pilot"], factSources };
}
const byId = (results: CheckResult[]) => Object.fromEntries(results.map((r) => [r.checkId, r]));

test("the Step 4 fixture is the checkpointed artifact, byte for byte", () => {
  const hash = createHash("sha256").update(readFileSync(path.join(repo, STEP4))).digest("hex");
  assert.equal(hash, "960b61bab2ff8a5247bf46c93fc167f12548bd496a218bc20a4818aae0ba8f37");
});

test("Step 4 artifact: the original six all pass it (the gap this milestone closes)", () => {
  const results = runChecks({ ...ctx(read(STEP4)), requiredSections: ["hero", "services", "packages", "process", "faq", "contact"] }, CHECK_REGISTRY);
  assert.deepEqual(results.filter((r) => !r.passed).map((r) => r.checkId), []);
});

test("Step 4 artifact FAILS the claims gate on leaked text, unlabelled testimonials and invented phone/hours", () => {
  const r = byId(runChecks(ctx(read(STEP4)), CLAIMS_CHECKS));
  assert.equal(r["claims.after-html"]!.passed, false);
  assert.match(r["claims.after-html"]!.details.join(" "), /File-mutation verifier/);

  assert.equal(r["claims.sample-label"]!.passed, false);
  assert.equal(r["claims.sample-label"]!.details.filter((d) => d.startsWith("Testimonial without")).length, 3, "one detail per testimonial card");

  const facts = r["claims.unsourced-fact"]!.details.join("\n");
  assert.equal(r["claims.unsourced-fact"]!.passed, false);
  assert.match(facts, /FACT-PHONE: phone number "\(555\) 014-7732"/);
  assert.match(facts, /FACT-HOURS: opening hours "7:00am"/);
  assert.match(facts, /FACT-PROMISE: time promise "within one business day"/);
  assert.match(facts, /FACT-AREA: service area "Maple Ridge"/i);

  assert.equal(r["claims.banned"]!.passed, false);
  assert.match(r["claims.banned"]!.details.join(" "), /BC-RATING: "★★★★★"/);
});

test("the brief's own SAMPLE phone is sourced; a labelled line does not excuse an invented one beside it", () => {
  const ok = `<!DOCTYPE html><html><body><ul><li>Call <a href="tel:5550142">555-0142</a> (SAMPLE number)</li></ul></body></html>`;
  assert.equal(runChecks(ctx(ok), CLAIMS_CHECKS).every((x) => x.passed), true);
  const bad = `<!DOCTYPE html><html><body><ul><li>Call 555-0142 (SAMPLE number)</li><li>Office (555) 014-7732</li></ul></body></html>`;
  assert.equal(byId(runChecks(ctx(bad), CLAIMS_CHECKS))["claims.unsourced-fact"]!.passed, false);
});

test("no fact sources: every factual claim is unsourced (fails closed)", () => {
  const { factSources: _omitted, ...noSources } = ctx("<!DOCTYPE html><html><body><p>Call 555-0142 today.</p></body></html>");
  const r = byId(runChecks(noSources, CLAIMS_CHECKS));
  assert.equal(r["claims.unsourced-fact"]!.passed, false);
  assert.match(r["claims.unsourced-fact"]!.details.join(" "), /No fact sources were supplied/);
});

test("clean fixture passes all 10 production QA checks (the six plus the claims gate)", () => {
  const results = runChecks(ctx(read("packages/frontend-loop/design/fixtures/clean.html")), QA_GATE_CHECKS);
  assert.equal(results.length, 10);
  for (const r of results) assert.deepEqual(r.details, [], `${r.checkId}: ${r.details.join("; ")}`);
});

const PLANTED: [fixture: string, checkId: string, expect: RegExp][] = [
  ["leaked-text", "claims.after-html", /File-mutation verifier/],
  ["missing-sample", "claims.sample-label", /Testimonial without a visible SAMPLE label/],
  ["invented-fact", "claims.unsourced-fact", /\(555\) 014-7732[\s\S]*Mon-Sat/],
  ["banned-claim", "claims.banned", /BC-LICENCE[\s\S]*BC-SUPERLATIVE[\s\S]*BC-YEARS/],
];
for (const [fixture, checkId, expect] of PLANTED) {
  test(`planted defect "${fixture}" fails ${checkId} and nothing else`, () => {
    const results = runChecks(ctx(read(`packages/verification/test/fixtures/claims/${fixture}.html`)), QA_GATE_CHECKS);
    assert.deepEqual(results.filter((r) => !r.passed).map((r) => r.checkId), [checkId]);
    assert.match(results.find((r) => r.checkId === checkId)!.details.join("\n"), expect);
  });
}

// --- VerificationLoop wiring for the new suites --------------------------------------------------

function suite(id: string, result: Partial<CheckResult>): AsyncCheckSuite & { calls: number } {
  const s = {
    id,
    description: id,
    calls: 0,
    async run(): Promise<CheckResult[]> {
      s.calls += 1;
      return [{ checkId: id, passed: true, details: [], ...result }];
    },
  };
  return s;
}
const cleanCtx = () => ctx(read("packages/frontend-loop/design/fixtures/clean.html"));

test("loop: Step 4 page fails the claims gate before any review or model call", async () => {
  const evaluator = new MockModelClient(() => "VERDICT: APPROVED");
  const review = suite("render.design-review", {});
  const result = await new VerificationLoop({ checks: QA_GATE_CHECKS, reviewSuites: [review], evaluatorModel: evaluator }).run(ctx(read(STEP4)), brief.goal);
  assert.equal(result.status, "failed_checks");
  assert.equal(review.calls, 0);
  assert.equal(evaluator.calls.length, 0);
});

test("loop: a failing async (browser) check is failed_checks, and the reviewer is not called", async () => {
  const review = suite("render.design-review", {});
  const result = await new VerificationLoop({
    checks: QA_GATE_CHECKS,
    asyncChecks: [suite("render.links", { passed: false, details: ["broken"] })],
    reviewSuites: [review],
    evaluatorModel: new MockModelClient(() => "VERDICT: APPROVED"),
  }).run(cleanCtx(), brief.goal);
  assert.equal(result.status, "failed_checks");
  assert.equal(review.calls, 0);
});

test("loop: a screenshot review that did not run is NOT verified (never a pass)", async () => {
  const evaluator = new MockModelClient(() => "VERDICT: APPROVED");
  const result = await new VerificationLoop({
    checks: QA_GATE_CHECKS,
    reviewSuites: [suite("render.design-review", { passed: false, notRun: true, details: ["no reviewer"] })],
    evaluatorModel: evaluator,
  }).run(cleanCtx(), brief.goal);
  assert.equal(result.status, "blocked_no_evaluator");
  assert.equal(evaluator.calls.length, 0);
});

test("loop: a failed screenshot review is changes_requested with its rule ids, evaluator not called", async () => {
  const evaluator = new MockModelClient(() => "VERDICT: APPROVED");
  const result = await new VerificationLoop({
    checks: QA_GATE_CHECKS,
    reviewSuites: [suite("render.design-review", { passed: false, details: ["DR-THREE-CARD-ROW: ..."] })],
    evaluatorModel: evaluator,
  }).run(cleanCtx(), brief.goal);
  assert.equal(result.status, "changes_requested");
  assert.equal(evaluator.calls.length, 0);
  assert.match(result.checkResults.find((c) => c.checkId === "render.design-review")!.details[0]!, /^DR-THREE-CARD-ROW/);
});

test("loop: review passes, then the evaluator still has to approve", async () => {
  const evaluator = new MockModelClient(() => "VERDICT: APPROVED");
  const result = await new VerificationLoop({
    checks: QA_GATE_CHECKS,
    reviewSuites: [suite("render.design-review", {})],
    evaluatorModel: evaluator,
  }).run(cleanCtx(), brief.goal);
  assert.equal(result.status, "approved");
  assert.equal(evaluator.calls.length, 1);
});
